In [35]:
faqs = """1. How do I apply?
You can apply online using the "Apply Now" form or submit a paper form via walk‑in admissions. After filling the form, you'll need to pay the registration fee, which will later be adjusted against your tuition fee
marwadiuniversity.ac.in
+10
marwadiuniversity.ac.in
+10
shiksha.com
+10
.

2. What is the medium of instruction?
All programs are taught in English
marwadiuniversity.online
+1
en.wikipedia.org
+1
.

3. What are the eligibility criteria?

Engineering: Based on JEE Main + Class XII marks, per ACPC handbook
marwadiuniversity.ac.in
+2
marwadiuniversity.ac.in
+2
marwadiuniversity.ac.in
+2
.

Architecture: NATA + Class XII marks
marwadiuniversity.ac.in
+1
marwadiuniversity.ac.in
+1
.

MBA/MCA: Through CMAT scores
adscientificindex.com
+7
marwadiuniversity.ac.in
+7
marwadiuniversity.ac.in
+7
.

4. What documents do I need at admission?
Bring originals + photocopies of SSC & HSC marksheets, school leaving certificate, JEE/Main/NATA/ACPC slip (for UG). For PG, include your Bachelor’s degree + marksheets and valid GATE/CMAT/CAT/GPAT scorecards (as applicable)
marwadiuniversity.ac.in
+1
marwadiuniversity.ac.in
+1
.

5. What is the admission process?

Apply online (or in-person)

Visit the campus for counseling/session

Submit documents (marksheets, ID proof)

Pay tuition via online channels or NEFT
marwadiuniversity.ac.in
marwadiuniversity.online
+3
marwadiuniversity.ac.in
+3
marwadiuniversity.ac.in
+3
.

6. How are admissions decided for PG?
Based on academic aptitude, performance in selection processes (e.g. CMAT), and eligibility criteria laid out in the brochure
marwadiuniversity.ac.in
.

💰 Fees, Scholarships & Loans
7. What about fees?
Fees differ by program. Check the relevant course page or contact Admissions for detailed information .

8. Are scholarships available?
Yes—opportunities include International Scholarships, GATE, GPAT, Vidhyalakshmi Yojana, and others. Reach out to Admissions for guidance
marwadiuniversity.ac.in
.

9. Is there a loan facility?
Yes—MU has partnerships with SBI, BoI, CBI, HDFC, and private banks for quick education loans
marwadiuniversity.ac.in
+1
marwadiuniversity.ac.in
+1
.

🏡 Facilities & Campus Life
10. Hostels?
Yes—6 hostels with ~3,500 capacity, separate for boys and girls; attached mess and modern amenities
marwadiuniversity.ac.in
+1
marwadiuniversity.ac.in
+1
.

11. Medical facility?
On‑campus first‑aid, emergency assistance, and a 24/7 ambulance. Collaborations with Sterling Hospital enhance medical services
marwadiuniversity.ac.in
+4
marwadiuniversity.ac.in
+4
propelld.com
+4
.

12. How to reach the campus?
Located on Rajkot–Morbi Road, approximately 10 km from bus stand/train station and 12 km from the airport. Accessible via city bus to Madhapar Chowk + rickshaw, or drive via Google Maps
marwadiuniversity.ac.in

marwadiuniversity.online
👩‍💼 Recognition & Placements
13. Is MU recognized?
Yes—UGC‑approved and holds an NAAC A+ grade, the highest in Gujarat
marwadiuniversity.ac.in
+1
marwadiuniversity.online
+1
.

14. How is placement support?
MU claims 100% placement assistance, with over 480 companies visiting last year. With consistent effort, students can land roles with notable packages
marwadiuniversity.ac.in
+1
marwadiuniversity.ac.in
+1
.


"""

In [36]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

In [37]:
tokenizer = Tokenizer()

In [38]:
tokenizer.fit_on_texts([faqs])

In [39]:
len(tokenizer.word_index)

252

In [40]:
input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
  print(tokenized_sentence)

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

[4, 14, 33, 34, 15]
[69, 35, 15, 8, 70, 5, 15, 71, 23, 10, 36, 16, 72, 23, 17, 73, 18, 74, 75, 5, 23, 76, 37, 19, 38, 5, 77, 39, 78, 79, 80, 81, 82, 83, 40, 41, 39]
[2, 3, 1]
[20]
[2, 3, 1]
[20]
[84, 24]
[20]
[]
[]
[21, 11, 25, 5, 85, 42, 86]
[87, 88, 26, 89, 1, 90]
[2, 8]
[4]
[91, 92, 93]
[4]
[]
[]
[12, 11, 26, 5, 43, 44]
[]
[94, 45, 27, 46, 47, 48, 49, 50, 95, 51, 96]
[2, 3, 1]
[21]
[2, 3, 1]
[21]
[2, 3, 1]
[21]
[]
[]
[97, 52, 48, 49, 50]
[2, 3, 1]
[4]
[2, 3, 1]
[4]
[]
[]
[98, 99, 100, 28, 101]
[102, 24]
[13]
[2, 3, 1]
[13]
[2, 3, 1]
[13]
[]
[]
[22, 11, 53, 33, 34, 37, 103, 54]
[104, 105, 106, 42, 107, 108, 29, 109, 110, 111, 46, 47, 52, 51, 112, 7, 113, 7, 55, 56, 40, 114, 115, 29, 6, 116, 57, 28, 117, 58, 118, 119, 120]
[2, 3, 1]
[4]
[2, 3, 1]
[4]
[]
[]
[121, 11, 25, 5, 54, 122]
[]
[15, 8, 10, 1, 123]
[]
[124, 5, 30, 7, 125, 126]
[]
[36, 53, 29, 127, 128]
[]
[38, 41, 17, 8, 129, 10, 130]
[2, 3, 1]
[2, 8]
[12]
[2, 3, 1]
[12]
[2, 3, 1]
[12]
[]
[]
[131, 14, 26, 18, 132, 7, 55]
[45, 27

In [41]:
input_sequences

[[4, 14],
 [4, 14, 33],
 [4, 14, 33, 34],
 [4, 14, 33, 34, 15],
 [69, 35],
 [69, 35, 15],
 [69, 35, 15, 8],
 [69, 35, 15, 8, 70],
 [69, 35, 15, 8, 70, 5],
 [69, 35, 15, 8, 70, 5, 15],
 [69, 35, 15, 8, 70, 5, 15, 71],
 [69, 35, 15, 8, 70, 5, 15, 71, 23],
 [69, 35, 15, 8, 70, 5, 15, 71, 23, 10],
 [69, 35, 15, 8, 70, 5, 15, 71, 23, 10, 36],
 [69, 35, 15, 8, 70, 5, 15, 71, 23, 10, 36, 16],
 [69, 35, 15, 8, 70, 5, 15, 71, 23, 10, 36, 16, 72],
 [69, 35, 15, 8, 70, 5, 15, 71, 23, 10, 36, 16, 72, 23],
 [69, 35, 15, 8, 70, 5, 15, 71, 23, 10, 36, 16, 72, 23, 17],
 [69, 35, 15, 8, 70, 5, 15, 71, 23, 10, 36, 16, 72, 23, 17, 73],
 [69, 35, 15, 8, 70, 5, 15, 71, 23, 10, 36, 16, 72, 23, 17, 73, 18],
 [69, 35, 15, 8, 70, 5, 15, 71, 23, 10, 36, 16, 72, 23, 17, 73, 18, 74],
 [69, 35, 15, 8, 70, 5, 15, 71, 23, 10, 36, 16, 72, 23, 17, 73, 18, 74, 75],
 [69, 35, 15, 8, 70, 5, 15, 71, 23, 10, 36, 16, 72, 23, 17, 73, 18, 74, 75, 5],
 [69,
  35,
  15,
  8,
  70,
  5,
  15,
  71,
  23,
  10,
  36,
  16,
  72,


In [42]:
max_len = max([len(x) for x in input_sequences])
# for x in input_sequences:
#   print(len(x))

print(max_len)

37


In [43]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [44]:
padded_input_sequences

array([[ 0,  0,  0, ...,  0,  4, 14],
       [ 0,  0,  0, ...,  4, 14, 33],
       [ 0,  0,  0, ..., 14, 33, 34],
       ...,
       [ 0,  0,  0, ...,  2,  3,  1],
       [ 0,  0,  0, ...,  0,  2,  3],
       [ 0,  0,  0, ...,  2,  3,  1]], dtype=int32)

In [45]:
X = padded_input_sequences[:,:-1]


print(X)

[[ 0  0  0 ...  0  0  4]
 [ 0  0  0 ...  0  4 14]
 [ 0  0  0 ...  4 14 33]
 ...
 [ 0  0  0 ...  0  2  3]
 [ 0  0  0 ...  0  0  2]
 [ 0  0  0 ...  0  2  3]]


In [46]:
y = padded_input_sequences[:,-1]
print(y)

[ 14  33  34  15  35  15   8  70   5  15  71  23  10  36  16  72  23  17
  73  18  74  75   5  23  76  37  19  38   5  77  39  78  79  80  81  82
  83  40  41  39   3   1   3   1  24  11  25   5  85  42  86  88  26  89
   1  90   8  92  93  11  26   5  43  44  45  27  46  47  48  49  50  95
  51  96   3   1   3   1   3   1  52  48  49  50   3   1   3   1  99 100
  28 101  24   3   1   3   1  11  53  33  34  37 103  54 105 106  42 107
 108  29 109 110 111  46  47  52  51 112   7 113   7  55  56  40 114 115
  29   6 116  57  28 117  58 118 119 120   3   1   3   1  11  25   5  54
 122   8  10   1 123   5  30   7 125 126  53  29 127 128  41  17   8 129
  10 130   3   1   8   3   1   3   1  14  26  18 132   7  55  27 133 134
 135   1 136 137 138 139  28   6  43  44 140  59   1   5 141   3   1  31
  32  60  11 143  31 144 145 146 147   5 148 149 150  10 151  18   7 152
 153 155  32 156  56 158  32  57  58 159 160   6 161  61  59  19  18   7
 162   3   1  62 164  16 165  63 167 168   9 169 17

In [47]:
X.shape

(387, 36)

In [48]:
y.shape

(387,)

In [49]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=1194)

In [50]:
y.shape

(387, 1194)

In [51]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [52]:
model = Sequential()
model.add(Embedding(1194, output_dim=100, input_length=X.shape[1]))
model.add(LSTM(150))
model.add(Dense(1194, activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [53]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [54]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [55]:
model.fit(X,y,epochs=20)

Epoch 1/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 4s 63ms/step - accuracy: 0.0453 - loss: 7.0500
Epoch 2/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.0660 - loss: 6.0153
Epoch 3/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - accuracy: 0.0901 - loss: 5.1712
Epoch 4/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 62ms/step - accuracy: 0.0873 - loss: 5.0459
Epoch 5/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 119ms/step - accuracy: 0.1038 - loss: 5.0731
Epoch 6/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 98ms/step - accuracy: 0.0907 - loss: 5.0665 
Epoch 7/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 60ms/step - accuracy: 0.0805 - loss: 5.0277
Epoch 8/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 62ms/step - accuracy: 0.0918 - loss: 4.8474
Epoch 9/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - accuracy: 0.0785 - loss: 4.8180
Epoch 10/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 62ms/step - accuracy: 0.1201 - loss: 4.8541
Epoch 11/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 67ms/step - accuracy: 0.1360 - loss: 4.7763
Epoch 12/20
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 66ms/step - accurac

In [56]:
import time
text = "Gujarat"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  print(model.predict(padded_token_text))

  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 239ms/step
[[5.9886102e-06 5.4374360e-02 4.4846415e-06 ... 8.3664918e-06
  5.2247733e-06 4.2724937e-06]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
Gujarat ac
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
[[2.3963068e-07 8.7162548e-01 1.8735177e-07 ... 3.8080486e-07
  2.1594350e-07 2.0815821e-07]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
Gujarat ac in
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[[1.9546300e-05 1.3980910e-02 1.6389400e-05 ... 2.5444726e-05
  1.8075580e-05 1.3845315e-05]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
Gujarat ac in the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
[[3.6659381e-05 6.7049987e-03 3.4655397e-05 ... 4.9201499e-05
  3.8298145e-05 3.0397607e-05]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
Gujarat ac in the the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[[3.6790454e-05 5.1452429e-03 3.8123231e-05 ... 5.1083505e-05
  4.1109528e-05 3.2643438e-05]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Gujarat ac in the the the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
[[3.6446309e-05 4.15

In [57]:
tokenizer.word_index

{'in': 1,
 'marwadiuniversity': 2,
 'ac': 3,
 '1': 4,
 'the': 5,
 'and': 6,
 'for': 7,
 'online': 8,
 'with': 9,
 'or': 10,
 '\u202fwhat': 11,
 '3': 12,
 '7': 13,
 '\u202fhow': 14,
 'apply': 15,
 'a': 16,
 'via': 17,
 'admissions': 18,
 'to': 19,
 '10': 20,
 '2': 21,
 '4': 22,
 'form': 23,
 'com': 24,
 'is': 25,
 'are': 26,
 'on': 27,
 'cmat': 28,
 'marksheets': 29,
 'campus': 30,
 'fees': 31,
 'scholarships': 32,
 'do': 33,
 'i': 34,
 'can': 35,
 'submit': 36,
 'need': 37,
 'pay': 38,
 'fee': 39,
 'your': 40,
 'tuition': 41,
 'of': 42,
 'eligibility': 43,
 'criteria': 44,
 'based': 45,
 'jee': 46,
 'main': 47,
 'class': 48,
 'xii': 49,
 'marks': 50,
 'acpc': 51,
 'nata': 52,
 'documents': 53,
 'admission': 54,
 'pg': 55,
 'include': 56,
 'gate': 57,
 'gpat': 58,
 'out': 59,
 'loans': 60,
 'reach': 61,
 '\u202fis': 62,
 'facility': 63,
 'assistance': 64,
 'from': 65,
 'bus': 66,
 'mu': 67,
 'placement': 68,
 'you': 69,
 'using': 70,
 'now': 71,
 'paper': 72,
 'walk‑in': 73,
 'after': 7